script_name("MP Helper")
script_authors("GORYCH")
script_description("Правила мп")
script_version("0.1")
script_dependencies("CLEO")

---------------------------------------------------------------------------
local hook = require 'lib.samp.events'
require 'lib.moonloader'

function main()
	while not isSampAvailable() do wait(3800) end
	sampAddChatMessage(("{00FA9A}MP HELPER v"..thisScript().version..'{FFD700} |{FFFFFF}Активация: {10bfeb}/mphelp{FFD700}|{FFFFFF} Автор: {00FA9A}GORYCH'), 0xFFFFFF)
	sampRegisterChatCommand("mphelp", func)
	Dialog = lua_thread.create_suspended(DialogFunc)
end

function func()
    Dialog:run()
end


function DialogFunc()
				
	local DialogText = "Бои\nБои(Стенка на стенку)\nВыбери Меня\nПоледняя реакция\nРодео\nПвп\nCounter-Strike\nСмертельный Выстрел\nГонка\nДерби\nДерби с напарником\nОдуванчики\nЗабег\nЗабег на роликах\nЗаплыв\nПовтори\nРусская Рулетка{00FA9A}(new){ffffff}"
	dialogId = 1100
	dialogButton = nil
	dialogListItem = nil
	dialogInput = nil
	dialogBool = false
	sampShowDialog(dialogId, "{FFFFFF}Выбор мп." , DialogText, "Выбрать", "Закрыть", 4)
	while not dialogBool do
		wait(0)
		dialogBool, dialogButton, dialogListItem, dialogInput = sampHasDialogRespond(dialogId)
	end
	if dialogButton ~= 0 then
    if dialogListItem == 0 then
	sampSendChat("/s Друзья, объясняю правила мероприятия \"Бои\":",0xffffff)
	wait(2000)
	sampSendChat("/s Я буду вызывать по 2 человека, которые должны ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... будут пополнить свои хп и ждать старта.",0xffffff)
	wait(2000)
	sampSendChat("/s После того как дам старт - нельзя будет ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... использовать любые средства пополнения хп.",0xffffff)
	wait(2000)
	sampSendChat("/s После старта вы должны будете убить оппонента ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... кулаком. Кто победит - идет в следующий ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... раунд. Правила всем ясны? /pm",0xffffff)
	elseif dialogListItem == 1 then
	sampSendChat("/s Объясняю правила мероприятия \" Бои(Стенка на стенку)\":",0xffffff)
	wait(2000)
	sampSendChat("/s Сначала я выбираю кепов.",0xffffff)
	wait(2000)
	sampSendChat("/s После этого кепы должны собрать команды.",0xffffff)
	wait(2000)
	sampSendChat("/s Затем команды становятся в два строя друг против друга.",0xffffff)
	wait(2000)
	sampSendChat("/s По старту игроки начинают драться.",0xffffff)
	wait(2000)
	sampSendChat("/s Уцелевшая сторона делится на две команды ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... если в ней более 3 игроков.",0xffffff)
	wait(2000)
	sampSendChat("/s Побеждает тот, кто останется последним. ",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 2 then
	sampSendChat("/s Объясняю правила мероприятия \" Выбери меня\":",0xffffff)
	wait(2000)
	sampSendChat("/s Сначала я напишу в чат чтобы вы приготовились.",0xffffff)
	wait(2000)
	sampSendChat("/s После этого вы должны ждать старта.",0xffffff)
	wait(2000)
	sampSendChat("/s Как прозвучит старт, это может быть что ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... угодно, как \"го\" так и \"Старт\" и т.д.,",0xffffff)
	wait(2000)
	sampSendChat("/s вы должны быстро отправить мне в /pm id игрока, ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... которого хотите кикнуть с ангара. Чей id ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... будет вторым в списке - тот и проиграл. ",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 3 then
	sampSendChat("/s Объясняю правила мероприятия \" Последняя Реакция\":",0xffffff)
	wait(2000)
	sampSendChat("/s Сначала я напишу в чат чтобы вы приготовились.",0xffffff)
	wait(2000)
	sampSendChat("/s После этого напишу любую анимацию, например: ",0xffffff)
	wait(2000)
	sampSendChat("/s /taichi",0xffffff)
	wait(2000)
	sampSendChat("/s Вы должны будете написать ее быстрее всех.",0xffffff)
	wait(2000)
	sampSendChat("/s Кто выполнит анимацию последним, тот и проиграл.",0xffffff)
	wait(2000)
	sampSendChat("/s Также выгоняется тот, кто вообще ничего не делал.",0xffffff)
	wait(2000)
	sampSendChat("/s Нельзя пользоваться скриптами, биндерами и т.п.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
elseif dialogListItem == 4 then
	sampSendChat("/s Объясняю правила мероприятия \" Родео\":",0xffffff)
	wait(2000)
	sampSendChat("/s По объявлению команды \"на самолет\" ...",0xffffff)
	wait(2000)
	sampSendChat("/s вы бежите на самолет. Только после команды ",0xffffff)
	wait(2000)
	sampSendChat("/s Затем вы ложитесь, садитесь или просто стоите.",0xffffff)
	wait(2000)
	sampSendChat("/s Я лечу над штатом и пытаюсь вас скинуть",0xffffff)
	wait(2000)
	sampSendChat("/s Кто останется на самолете или улетит ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... последним - выиграл. ",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 5 then
	sampSendChat("/s Объясняю правила мероприятия \" P v P\":",0xffffff)
	wait(2000)
	sampSendChat("/s Сначала я вызываю двух игроков",0xffffff)
	wait(2000)
	sampSendChat("/s Они выходят и принимают таблетки",0xffffff)
	wait(2000)
	sampSendChat("/s Если более 100хп - дисквалификация",0xffffff)
	wait(2000)
	sampSendChat("/s Затем я дам старт и они должны будут ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... убить друг друга. Кто выиграл -  ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... включает /cvet 3 и бежит на другую сторону.",0xffffff)
	wait(2000)
	sampSendChat("/s Выиграет тот, кто победит в финале.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 6 then
	sampSendChat("/s Объясняю правила мероприятия \" C S\":",0xffffff)
	wait(2000)
	sampSendChat("/s Я выбираю 2-х капитанов, которые должны будут ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... выбрать игроков. После жеребьёвки капитаны ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... по очереди выбирают игроков. Кого выбрали -...",0xffffff)
	wait(2000)
	sampSendChat("/s ... включает цвет капитана и идут на место, ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... которое выбрал их командир.",0xffffff)
	wait(2000)
	sampSendChat("/s Выиграет та команда, которая победит в финале.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 7 then
	sampSendChat("/s Объясняю правила мероприятия \" С В\":",0xffffff)
	wait(2000)
	sampSendChat("/s Я выбираю 2-х капитанов, которые должны будут ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... выбрать игроков. После жеребьёвки капитаны ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... по очереди выбирают игроков. Кого выбрали -...",0xffffff)
	wait(2000)
	sampSendChat("/s ... включает цвет капитана и идут на место, ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... которое выбрал их командир.",0xffffff)
	wait(2000)
	sampSendChat("/s Затем вам дадут 45хп. Разрешен только Desert Eagle.",0xffffff)
	wait(2000)
	sampSendChat("/s Выиграет та команда, которая победит в финале.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 8 then
	sampSendChat("/s Объясняю правила мероприятия \" Гонка\":",0xffffff)
	wait(2000)
	sampSendChat("/s Вы должны стоять тут и ждать старта.",0xffffff)
	wait(2000)
	sampSendChat("/s Кто поедет до старта - дисквалификация.",0xffffff)
	wait(2000)
	sampSendChat("/s Старт с местом финиша будет дан в /news. ",0xffffff)
	wait(2000)
	sampSendChat("/s Кто первый доедет - победил.",0xffffff)
	wait(2000)
	sampSendChat("/s Если вы взорвались - проиграли.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 9 then
	sampSendChat("/s Объясняю правила мероприятия \" Дерби\":",0xffffff)
	wait(2000)
	sampSendChat("/s Выбираем каждый свой /cvet.",0xffffff)
	wait(2000)
	sampSendChat("/s Я дам старт в /news. Вы должны ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... будете врезаться в других игроков, ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... чтобы взорвать их. Кто останется, тот ... ",0xffffff)
	wait(2000)
	sampSendChat("/s ... выиграл. Выходить из машины нельзя.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 10 then
	sampSendChat("/s Объясняю правила мероприятия \" Дерби с напарником\":",0xffffff)
	wait(2000)
	sampSendChat("/s Каждая пара выбирает свой /cvet.",0xffffff)
	wait(2000)
	sampSendChat("/s Я дам старт в /news. Вы должны будете ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... врезаться и стрелять в машины других ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... игроков, чтобы взорвать их. ",0xffffff)
	wait(2000)
	sampSendChat("/s Кто останется, тот и выиграл. ",0xffffff)
	wait(2000)
	sampSendChat("/s Выходить из машины нельзя.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 11 then
	sampSendChat("/s Объясняю правила мероприятия \" Одуванчики\":",0xffffff)
	wait(2000)
	sampSendChat("/s Вы должны дождаться старта.",0xffffff)
	wait(2000)
	sampSendChat("/s Старт с местом финиша будет дан в /news. ",0xffffff)
	wait(2000)
	sampSendChat("/s Как дам старт - вы должны прыгнуть и ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... приземлиться на мое транспортное средство. ",0xffffff)
	wait(2000)
	sampSendChat("/s Кто прилетит первый, тот и выиграл. ",0xffffff)
	wait(2000)
	sampSendChat("/s Кто прилетит рядом - не считается.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 12 then
	sampSendChat("/s Объясняю правила мероприятия \" Забег\":",0xffffff)
	wait(2000)
	sampSendChat("/s Вы должны стоять тут и ждать старта.",0xffffff)
	wait(2000)
	sampSendChat("/s Как дам старт - вы должны будете ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... добежать до меня. Первый - победил.",0xffffff)
	wait(2000)
	sampSendChat("/s Кто ударит кулаком - дисквалификация.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 13 then
	sampSendChat("/s Объясняю правила мероприятия \" Забег на роликах\":",0xffffff)
	wait(2000)
	sampSendChat("/s Вы должны стоять тут и ждать старта.",0xffffff)
	wait(2000)
	sampSendChat("/s Как дам старт - вы должны будете ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... добежать до меня. Первый - победил.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 14 then
	sampSendChat("/s Объясняю правила мероприятия \" Заплыв\":",0xffffff)
	wait(2000)
	sampSendChat("/s Вы должны стоять тут и ждать старта.",0xffffff)
	wait(2000)
	sampSendChat("/s Как дам старт - вы должны будете ...",0xffffff)
	wait(2000)
	sampSendChat("/s ... доплыть до меня. Первый - победил.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
	elseif dialogListItem == 15 then
	sampSendChat("/s Объясняю правила мероприятия \" Повтори\":",0xffffff)
	wait(2000)
	sampSendChat("/s Сначала я напишу в чат чтобы вы приготовились.",0xffffff)
	wait(2000)
	sampSendChat("/s После этого выполню любую анимацию, например: ",0xffffff)
	wait(2000)
	sampSendChat("/piss",0xffffff)
	wait(2000)
	sampSendChat("/s Вы должны будете повторить ее быстрее всех.",0xffffff)
	wait(2000)
	sampSendChat("/s Кто выполнит анимацию последним, тот и проиграл.",0xffffff)
	wait(2000)
	sampSendChat("/s Также выгоняется тот, кто вообще ничего не делал.",0xffffff)
	wait(2000)
	sampSendChat("/s Нельзя пользоваться скриптами, биндерами и т.п.",0xffffff)
	wait(2000)
	sampSendChat("/s Правила всем ясны? Отвечаем в /pm",0xffffff)
    elseif dialogListItem == 16 then
	sampSendChat("/s Друзья, объясняю правила мероприятия \" Русская Рулетка\":                       ",0xffffff)
	wait(2000)
	sampSendChat("/s Есть револьвер с вместимостью барабана в 8 пуль...                       ",0xffffff)                                    
	wait(2000)
	sampSendChat("/s В барабане сначала одна пуля. Потом буду добавлять.                      ",0xffffff)
	wait(2000)
	sampSendChat("/s Я буду подходить к каждому игроку по очереди.                      ",0xffffff)
	wait(2000)
	sampSendChat("/s Вам нужно выбрать, прокрутить барабан и ...                       ",0xffffff)
	wait(2000)
	sampSendChat("/s ... сделать выстрел или же сразу стрельнуть.                        ",0xffffff)
	wait(2000)
	sampSendChat("/news Команды \"крутить\" и \"выстрел\".                       ",0xffffff)
	wait(2000)
	sampSendChat("/s Кто напишет вне очереди - /akick. Флудить так же не надо.                        ",0xffffff)
	wait(2000)
	sampSendChat("/s Написали команду и ждёте ответа. Тролли сразу /akick, ...                        ",0xffffff)
	wait(2000)
	sampSendChat("/s ... разбираться не будем. Крутить барабан можно ...                        ",0xffffff)
	wait(2000)
	sampSendChat("/s ... максимум 3 раза. Можно и не крутить. Выиграет тот, ...                        ",0xffffff)
	wait(2000)
	sampSendChat("/s ... кто не убьет себя. Правила всем ясны? Отвечаем в /pm.                        ",0xffffff)
	end		
end
end
